### ISSUE TITLE
Type inconsistent error on Control request

### ISSUE THREAD

**Issue by anoshin** [tekvel/iedexplorer#2]
In some cases control request issued by IED explorer results in TYPE-INCONSISTENT error.

Failure does not happen every time. It was detected when trying to operate an IED after reboot. Specifically the controllable object has been in the intermediate state. The only obvious difference seen between failed and succeeded control requests is difference in padding as can be seen from the screenshot below

![image](https://user-images.githubusercontent.com/30081101/107425780-75917000-6b30-11eb-9d8c-2e259ad54a3b.png)

After the first successful control operation IEDExplorer won't fail anymore

**Comment by FireBrizz** [comment]
@anoshin Please give step-by-step instructions on how to reproduce the problem.
